export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const ADD_MEMORIES_SUCCESS = "ADD_MEMORIES_SUCCESS";
export const ADD_MEMORIES_FAILED = "ADD_MEMORIES_FAILED";

export const GET_ALL_MEMORIES_SUCCESS = "GET_ALL_MEMORIES_SUCCESS";
export const GET_ALL_MEMORIES_FAILED = "GET_ALL_MEMORIES_FAILED";

export const GET_SINGLE_MEMORY_SUCCESS = "GET_SINGLE_MEMORY_SUCCESS";
export const GET_SINGLE_MEMORY_FAILED = "GET_SINGLE_MEMORY_FAILED";

export const EDIT_MEMORIES_SUCCESS = "EDIT_MEMORIES_SUCCESS";
export const EDIT_MEMORIES_FAILED = "EDIT_MEMORIES_FAILED";

export const DELETE_MEMORIES_SUCCESS = "DELETE_MEMORIES_SUCCESS";
export const DELETE_MEMORIES_FAILED = "DELETE_MEMORIES_FAILED";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILED = "ADD_COMMENT_FAILED";

export const LOADING = "LOADING";
export const NOT_LOADING = "NOT_LOADING";

export const LOGOUT = "LOGOUT";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const RESET_STATUS = "RESET_STATUS";

export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILED = "LIKE_POST_FAILED";